//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaiDanh.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Văn A")]
        public string save_cbNguoiNhanTen {
            get {
                return ((string)(this["save_cbNguoiNhanTen"]));
            }
            set {
                this["save_cbNguoiNhanTen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bình Định")]
        public string save_cbNguoiNhanDiaChi {
            get {
                return ((string)(this["save_cbNguoiNhanDiaChi"]));
            }
            set {
                this["save_cbNguoiNhanDiaChi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lý do xuất kho")]
        public string save_cbKhoLyDo {
            get {
                return ((string)(this["save_cbKhoLyDo"]));
            }
            set {
                this["save_cbKhoLyDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xuất tại kho")]
        public string save_cbKhoXuatTai {
            get {
                return ((string)(this["save_cbKhoXuatTai"]));
            }
            set {
                this["save_cbKhoXuatTai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Địa điểm kho")]
        public string save_cbKhoDiaDiem {
            get {
                return ((string)(this["save_cbKhoDiaDiem"]));
            }
            set {
                this["save_cbKhoDiaDiem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tên hàng hoá")]
        public string save_cbHHTen {
            get {
                return ((string)(this["save_cbHHTen"]));
            }
            set {
                this["save_cbHHTen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_cbHHMaSo {
            get {
                return ((string)(this["save_cbHHMaSo"]));
            }
            set {
                this["save_cbHHMaSo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_cbHHDonVi {
            get {
                return ((string)(this["save_cbHHDonVi"]));
            }
            set {
                this["save_cbHHDonVi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_cbSoLuongYeuCau {
            get {
                return ((string)(this["save_cbSoLuongYeuCau"]));
            }
            set {
                this["save_cbSoLuongYeuCau"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_cbSoLuongThucXuat {
            get {
                return ((string)(this["save_cbSoLuongThucXuat"]));
            }
            set {
                this["save_cbSoLuongThucXuat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_cbHHDonGia {
            get {
                return ((string)(this["save_cbHHDonGia"]));
            }
            set {
                this["save_cbHHDonGia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_cbHHGhiChu {
            get {
                return ((string)(this["save_cbHHGhiChu"]));
            }
            set {
                this["save_cbHHGhiChu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool save_cbAutoFillDataNN {
            get {
                return ((bool)(this["save_cbAutoFillDataNN"]));
            }
            set {
                this["save_cbAutoFillDataNN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool save_cbAutoFillDataHH {
            get {
                return ((bool)(this["save_cbAutoFillDataHH"]));
            }
            set {
                this["save_cbAutoFillDataHH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999")]
        public string save_tbSoPhieu {
            get {
                return ((string)(this["save_tbSoPhieu"]));
            }
            set {
                this["save_tbSoPhieu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal save_nSoLanIn {
            get {
                return ((decimal)(this["save_nSoLanIn"]));
            }
            set {
                this["save_nSoLanIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BẬT")]
        public string save_cbSheetTrangThai {
            get {
                return ((string)(this["save_cbSheetTrangThai"]));
            }
            set {
                this["save_cbSheetTrangThai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://docs.google.com/spreadsheets/d/1eW1mLm7agFCN9jWPgqpFf7ICqasEYiljmF5KQUfbT" +
            "E4/edit#gid=0")]
        public string save_tbSheetURL {
            get {
                return ((string)(this["save_tbSheetURL"]));
            }
            set {
                this["save_tbSheetURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string save_tbSpreadSheetID {
            get {
                return ((string)(this["save_tbSpreadSheetID"]));
            }
            set {
                this["save_tbSpreadSheetID"] = value;
            }
        }
    }
}
